name: PHP converter

on:
  workflow_dispatch:
  schedule:
  - cron: "10 */24 * * *"
  # Updates every 24 hours at 10mins past the hour.

permissions:
  contents: write

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull latest changes # In case any changes are made recently
      run: git pull origin master

    - name: Make converter.php executable # If it is not already
      run: chmod +x converter.php
      
    - name: Use converter
      run: php ./converter.php

    - name: Commit files
      run: ./.check.sh

    - name: Push Changes
      run: git push origin master
